// Generated by FlutterFire CLI — regenerate with `flutterfire configure`.
// ignore_for_file: type=lint, lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web: uses the same API key as Android (same Firebase project).
  // Register a web app in Firebase Console and paste its appId below to
  // enable full analytics / crash reporting; Auth works with the stub appId.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_n6dWDJsc_8jQ4dKX2OtEt7IpCl60Doo',
    appId: '1:197359666307:web:0000000000000000',
    messagingSenderId: '197359666307',
    projectId: 'todo-niranjan',
    authDomain: 'todo-niranjan.firebaseapp.com',
    storageBucket: 'todo-niranjan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_n6dWDJsc_8jQ4dKX2OtEt7IpCl60Doo',
    appId: '1:197359666307:android:80f841812bb2ac2195c7b6',
    messagingSenderId: '197359666307',
    projectId: 'todo-niranjan',
    storageBucket: 'todo-niranjan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaGuCoZfSu6lZV8Q8eql6o6sFw5Zp7BzM',
    appId: '1:197359666307:ios:78a3183ab39a7c3c95c7b6',
    messagingSenderId: '197359666307',
    projectId: 'todo-niranjan',
    storageBucket: 'todo-niranjan.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  // macOS uses the same config as iOS.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaGuCoZfSu6lZV8Q8eql6o6sFw5Zp7BzM',
    appId: '1:197359666307:ios:78a3183ab39a7c3c95c7b6',
    messagingSenderId: '197359666307',
    projectId: 'todo-niranjan',
    storageBucket: 'todo-niranjan.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
